export enum UnitType {
    UT_Undefined = -2,
    UT_Custom = -1,
    UT_Length = 0,
    UT_Area = 1,
    UT_Volume = 2,
    UT_Angle = 3,
    UT_Number = 4,
   UT_Stress = 45,
    UT_UnitWeight = 46,
    UT_Piping_Volume = 55,
    UT_Currency = 72,
    UT_Displacement_Deflection = 95,
    UT_Energy = 96,
    UT_Mass = 98,
    UT_Surface_Area = 101,
    UT_Period = 102,
    UT_Rotation = 108,
    UT_Weight = 115,
    UT_MassDensity = 122,
    UT_MassPerUnitArea = 123,
}


export enum ViewType {
    Undefined = 0,
    FloorPlan = 1,
    CeilingPlan = 2,
    Elevation = 3,
    ThreeD = 4,
    Schedule = 5,
    DrawingSheet = 6,
    ProjectBrowser = 7,
    Report = 8,
    DraftingView = 10,
    Legend = 11,
    SystemBrowser = 12,
    EngineeringPlan = 115,
    AreaPlan = 116,
    Section = 117,
    Detail = 118,
    CostReport = 119,
    LoadsReport = 120,
    PresureLossReport = 121,
    ColumnSchedule = 122,
    PanelSchedule = 123,
    Walkthrough = 124,
    Rendering = 125,
    Internal = 214,
}

